import { describe, it, expect, afterEach } from 'vitest';
import { Clawck } from '../src/core/clawck';
import { makeTmpConfig } from './helpers';
import { generateTimesheetHTML } from '../src/reports/html';
import { generateTimesheetPDF, PDFReportOptions } from '../src/reports/pdf';
import { ReportBranding } from '../src/core/types';
import fs from 'fs';
import path from 'path';
import os from 'os';

let clawck: Clawck;

afterEach(() => {
  try { clawck?.close(); } catch {}
});

async function setup(configOverrides = {}) {
  clawck = await new Clawck(makeTmpConfig(configOverrides)).ready();
  return clawck;
}

async function seedData(c: Clawck) {
  c.log({ task: 'Test task 1', duration_minutes: 120, project: 'proj1', client: 'acme' });
  c.log({ task: 'Test task 2', duration_minutes: 60, project: 'proj2', client: 'acme' });
}

// ─── HTML Report Branding ─────────────────────────────────

describe('White-Label: HTML Reports', () => {
  it('includes company name in title', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const branding: ReportBranding = {
      company_name: 'Acme Corp',
    };

    const html = generateTimesheetHTML(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      branding,
    });

    expect(html).toContain('Acme Corp');
    expect(html).toContain('<title>Acme Corp');
  });

  it('applies custom primary color', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const branding: ReportBranding = {
      primary_color: '#ff5500',
    };

    const html = generateTimesheetHTML(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      branding,
    });

    expect(html).toContain('--accent: #ff5500');
  });

  it('includes custom footer text', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const branding: ReportBranding = {
      footer_text: 'Custom Footer Message',
    };

    const html = generateTimesheetHTML(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      branding,
    });

    expect(html).toContain('Custom Footer Message');
  });

  it('hides Clawck branding when requested', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const branding: ReportBranding = {
      hide_clawck_branding: true,
    };

    const html = generateTimesheetHTML(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      branding,
    });

    expect(html).not.toContain('Generated by Clawck');
  });

  it('includes custom CSS', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const branding: ReportBranding = {
      custom_css: '.custom-class { color: red; }',
    };

    const html = generateTimesheetHTML(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      branding,
    });

    expect(html).toContain('.custom-class { color: red; }');
  });

  it('includes base64 logo', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const branding: ReportBranding = {
      logo_base64: 'dGVzdGxvZ28=', // "testlogo" in base64
    };

    const html = generateTimesheetHTML(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      branding,
    });

    expect(html).toContain('data:image/png;base64,dGVzdGxvZ28=');
  });
});

// ─── PDF Report Branding ─────────────────────────────────

describe('White-Label: PDF Reports', () => {
  it('generates PDF with company name', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'clawck-test-'));
    const outputPath = path.join(tmpDir, 'test-report.pdf');

    const branding: ReportBranding = {
      company_name: 'Acme Corp',
    };

    await generateTimesheetPDF(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      outputPath,
      branding,
    });

    expect(fs.existsSync(outputPath)).toBe(true);
    const pdfContent = fs.readFileSync(outputPath);
    expect(pdfContent.length).toBeGreaterThan(0);

    // Cleanup
    fs.rmSync(tmpDir, { recursive: true });
  });

  it('generates PDF without Clawck branding', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'clawck-test-'));
    const outputPath = path.join(tmpDir, 'no-branding.pdf');

    const branding: ReportBranding = {
      hide_clawck_branding: true,
      footer_text: 'Custom Only Footer',
    };

    await generateTimesheetPDF(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      outputPath,
      branding,
    });

    expect(fs.existsSync(outputPath)).toBe(true);

    // Cleanup
    fs.rmSync(tmpDir, { recursive: true });
  });

  it('generates PDF with custom primary color', async () => {
    const c = await setup();
    await seedData(c);

    const ts = c.timesheet('2024-01-01', '2024-12-31');
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'clawck-test-'));
    const outputPath = path.join(tmpDir, 'colored.pdf');

    const branding: ReportBranding = {
      primary_color: '#e91e63',
    };

    await generateTimesheetPDF(ts, {
      dateRange: '2024-01-01 to 2024-12-31',
      outputPath,
      branding,
    });

    expect(fs.existsSync(outputPath)).toBe(true);

    // Cleanup
    fs.rmSync(tmpDir, { recursive: true });
  });
});

// ─── ReportBranding Type ─────────────────────────────────

describe('ReportBranding Type', () => {
  it('all branding fields are optional', () => {
    const empty: ReportBranding = {};
    expect(empty).toBeDefined();

    const partial: ReportBranding = {
      company_name: 'Test',
    };
    expect(partial.company_name).toBe('Test');
    expect(partial.logo_path).toBeUndefined();
  });

  it('supports all branding options', () => {
    const full: ReportBranding = {
      company_name: 'Full Corp',
      logo_path: '/path/to/logo.png',
      logo_base64: 'base64data',
      primary_color: '#123456',
      accent_color: '#654321',
      footer_text: 'Custom Footer',
      hide_clawck_branding: true,
      custom_css: '.test { }',
      font_family: 'Arial',
    };

    expect(full.company_name).toBe('Full Corp');
    expect(full.hide_clawck_branding).toBe(true);
    expect(full.primary_color).toBe('#123456');
  });
});
